# Generated by Django 5.0.4 on 2024-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='platform',
            field=models.CharField(choices=[('trendyol', 'Trendyol'), ('hepsiburada', 'Hepsiburada'), ('amazon', 'Amazon')], max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_url',
            field=models.URLField(unique=True),
        ),
    ]
